site_name: PKS2 - Project 1
site_author: Dominik Lichnovský
site_description: Project 1 and documentation of it

# Repository 
repo_name: PKS2-Project1
repo_url: https://github.com/JersyJ/PKS2-Project1

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - tables

nav:
  - General: index.md
  - Incoming packets: incoming_packets.md
  - Total incomed packets: incoming_packets_total.md
  - Developer documentation:
    - SNMP setup: dev/setup_snmp.md
    - Create RR Database:  dev/create_rr_database.md
    - Ingest Script:  dev/ingest_script.md
    - Timer setup:   dev/setup_timer.md
    - Nginx setup:  dev/setup_nginx.md
